function [fhatSPIRAL] = reconstruct1D (y, A)
% Run the algorithm:
% Demonstrating all the options for our algorithm:
    [fhatSPIRAL, iterationsSPIRAL, objectiveSPIRAL,...
        reconerrorSPIRAL, cputimeSPIRAL] ...
        = SPIRALTAP(y',ANT,tau,...
        'maxiter',maxiter,...
        'Initialization',finit,...
        'AT',AT,...
        'miniter',5,...
        'stopcriterion',3,...
        'tolerance',tolerance,...
        'alphainit',1,...
        'alphamin', 1e-30,...
        'alphamax', 1e30,...
        'alphaaccept',1e30,...
        'logepsilon',1e-10,...
        'saveobjective',1,...
        'savereconerror',1,...
        'savecputime',1,...
        'savesolutionpath',0,...
        'truth',f',...
        'noisetype','gaussian',...
        'verbose',verbose);
end
